export const LOAD_SIGNUPS_SUCCESS = 'LOAD_SIGNUPS_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_SIGNUP_SUCCESS = 'CREATE_SIGNUP_SUCCESS';
export const UPDATE_SIGNUP_SUCCESS = 'UPDATE_SIGNUP_SUCCESS';
export const AJAX_LOADING = 'AJAX_LOADING';
